#!/bin/bash

php app/console doctrine:database:drop --env dev --if-exists --force --no-interaction
php app/console doctrine:database:create --env dev --no-interaction
php app/console doctrine:schema:create --env dev --no-interaction
php app/console doctrine:fixtures:load --env dev --no-interaction
php app/console fos:elastica:populate
sudo chmod a+w -R web/
composer run-script post-install-cmd
php app/console bazinga:js-translation:dump --env dev --no-interaction
php app/console fos:js-routing:dump --env dev --no-interaction
php app/console cache:warmup --no-interaction --env dev
sudo setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs
sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs
